spring:
  application:
    name: cinebook-back
  datasource:
    url: jdbc:mariadb://localhost:3306/cinebook
    username: chris2003
    password: Chris.2003
    driver-class-name: org.mariadb.jdbc.Driver
  flyway:
    url: jdbc:mariadb://localhost:3306/cinebook
    user: chris2003
    password: Chris.2003
  jpa:
    show-sql: true
  jwt:
    security:
      key: 94c9284471e16a5cff6a59e8bd13c96e7b1e1661b6df7190a403e99787620035
server:
  max-http-request-header-size: 64KB
logging:
  level.com:
    zaxxer:
      hikari: DEBUG
  level.org:
    springframework:
      web: DEBUG

