spring:
  application:
    name: cinebook-back
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  flyway:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  jwt:
    security:
      key: 94c9284471e16a5cff6a59e8bd13c96e7b1e1661b6df7190a403e99787620035
server:
  max-http-request-header-size: 64KB
logging:
  level.com:
    zaxxer:
      hikari: DEBUG
  level.org:
    springframework:
      web: DEBUG
      security: DEBUG